[package]
name = "jset_desk"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk        = "^1.2"
lazy_static = "^1.4"
num_cpus    = "^1.13"